// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryofmnsrpwoiamrombon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5b2ZtbnNycHdvaWFtcm9tYm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNjM5MjQsImV4cCI6MjA1NjczOTkyNH0.OxpluixV_NByrcjbH3M7xChoh1EiqiHdbCYVT6BhrbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);